# export_to_header.py
# Run this on your PC: python export_to_header.py
# It will generate weights.h and vocab.h for Arduino

import torch
import pickle
import numpy as np
import struct
import os
from model import MicroLLM
import config

output_folder = "ESP32_code"  # Change this to your desired folder name
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

print("Loading vocab...")
with open('vocab.pkl', 'rb') as f:
    vocab_data = pickle.load(f)

stoi = vocab_data['stoi']
itos = vocab_data['itos']
vocab_size = vocab_data['vocab_size']
print(f"Vocab size: {vocab_size}")

print("Loading model...")
model = MicroLLM(vocab_size)
model.load_state_dict(torch.load('model.bin', map_location='cpu'))
model.eval()

total_params = sum(p.numel() for p in model.parameters())
total_bytes  = total_params * 4  # float32
print(f"Total parameters : {total_params:,}")
print(f"Estimated flash   : {total_bytes/1024:.1f} KB")

# ESP32 DevKit V1 has 4 MB flash. Warn if model is large.
if total_bytes > 3 * 1024 * 1024:
    print("WARNING: Model may be too large for ESP32 flash!")
else:
    print("Model fits comfortably in ESP32 flash.")

def tensor_to_c_array(tensor, name):
    """Convert a tensor to a C float array stored in PROGMEM."""
    data = tensor.detach().numpy().astype(np.float32).flatten()
    hex_vals = ['0x' + b.hex() for b in [struct.pack('<f', v) for v in data]]
    
    lines = []
    lines.append(f"// Shape: {list(tensor.shape)}, Elements: {len(data)}")
    lines.append(f"const float {name}[{len(data)}] PROGMEM = {{")
    
    # 8 values per line for readability
    chunk_size = 8
    for i in range(0, len(data), chunk_size):
        chunk = data[i:i+chunk_size]
        formatted = ', '.join(f'{v:.8f}f' for v in chunk)
        comma = ',' if i + chunk_size < len(data) else ''
        lines.append(f"  {formatted}{comma}")
    
    lines.append("};")
    lines.append(f"const int {name}_SIZE = {len(data)};")
    lines.append("")
    return '\n'.join(lines)

print("\nExporting weights to weights.h ...")
sd = model.state_dict()

with open(os.path.join(output_folder, 'weights.h'), 'w') as f:
    f.write("// Auto-generated by export_to_header.py\n")
    f.write("// DO NOT EDIT MANUALLY\n")
    f.write("#pragma once\n")
    f.write('#include <pgmspace.h>\n\n')
    
    # Model hyperparameters as #defines
    f.write(f"#define VOCAB_SIZE   {vocab_size}\n")
    f.write(f"#define EMBED_SIZE   {config.EMBED_SIZE}\n")
    f.write(f"#define NUM_HEADS    {config.NUM_HEADS}\n")
    f.write(f"#define NUM_LAYERS   {config.NUM_LAYERS}\n")
    f.write(f"#define BLOCK_SIZE   {config.BLOCK_SIZE}\n")
    f.write(f"#define HEAD_SIZE    {config.EMBED_SIZE // config.NUM_HEADS}\n\n")
    
    # Export every weight tensor
    key_map = {
        'token_embedding.weight'    : 'tok_emb',
        'position_embedding.weight' : 'pos_emb',
        'ln_f.weight'               : 'ln_f_w',
        'ln_f.bias'                 : 'ln_f_b',
        'lm_head.weight'            : 'lm_head_w',
    }
    for layer_i in range(config.NUM_LAYERS):
        key_map[f'blocks.{layer_i}.ln_1.weight']         = f'b{layer_i}_ln1_w'
        key_map[f'blocks.{layer_i}.ln_1.bias']           = f'b{layer_i}_ln1_b'
        key_map[f'blocks.{layer_i}.ln_2.weight']         = f'b{layer_i}_ln2_w'
        key_map[f'blocks.{layer_i}.ln_2.bias']           = f'b{layer_i}_ln2_b'
        key_map[f'blocks.{layer_i}.attn.c_attn.weight']  = f'b{layer_i}_attn_qkv_w'
        key_map[f'blocks.{layer_i}.attn.c_proj.weight']  = f'b{layer_i}_attn_proj_w'
        key_map[f'blocks.{layer_i}.mlp.0.weight']        = f'b{layer_i}_mlp_fc_w'
        key_map[f'blocks.{layer_i}.mlp.0.bias']          = f'b{layer_i}_mlp_fc_b'
        key_map[f'blocks.{layer_i}.mlp.2.weight']        = f'b{layer_i}_mlp_proj_w'
        key_map[f'blocks.{layer_i}.mlp.2.bias']          = f'b{layer_i}_mlp_proj_b'
    
    for sd_key, c_name in key_map.items():
        if sd_key in sd:
            print(f"  Exporting {sd_key} -> {c_name}")
            f.write(tensor_to_c_array(sd[sd_key], c_name))
        else:
            print(f"  SKIPPED (not found): {sd_key}")

print("weights.h written!")

# ── vocab.h ──────────────────────────────────────────────────────────────────
print("\nExporting vocab to vocab.h ...")
with open(os.path.join(output_folder, 'vocab.h'), 'w') as f:
    f.write("// Auto-generated by export_to_header.py\n")
    f.write("#pragma once\n\n")
    
    # itos: index -> char  (stored as a char array in PROGMEM)
    f.write(f"const char ITOS[{vocab_size}] PROGMEM = {{\n  ")
    entries = []
    for i in range(vocab_size):
        ch = itos[i]
        if ch == "'":
            entries.append("'\\''")
        elif ch == '\\':
            entries.append("'\\\\'")
        elif ch == '\n':
            entries.append("'\\n'")
        elif ch == '\r':
            entries.append("'\\r'")
        elif ch == '\t':
            entries.append("'\\t'")
        else:
            entries.append(f"'{ch}'")
    f.write(', '.join(entries))
    f.write("\n};\n\n")
    
    # stoi: char -> index  (stored as a lookup table, max char value 127)
    max_char = 128
    stoi_table = [-1] * max_char
    for ch, idx in stoi.items():
        if ord(ch) < max_char:
            stoi_table[ord(ch)] = idx
    
    f.write(f"const int16_t STOI[{max_char}] PROGMEM = {{\n  ")
    f.write(', '.join(str(v) for v in stoi_table))
    f.write("\n};\n")

print("vocab.h written!")
print("\nDone! Copy weights.h and vocab.h into your Arduino sketch folder.")
print(f"Flash usage estimate: {total_bytes/1024:.1f} KB / ~3000 KB available")